spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url:jdbc:postgresql://localhost:5432/mainDb}
    username: ${db.username:root}
    password: ${db.password:1234}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 100MB
      max-request-size: 200MB
  messages:
    basename: messages,config.i18n.messages
    encoding: UTF-8
          
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true    
    
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
